name: "apkbuild"
on:
  push:
    branches:
      - master
    paths:
      - apk/**

  pull_request: 
    types: [opened, synchronize, reopened]
    paths:
      - apk/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # These versions must be strings. E.g. Otherwise `3.10` -> `3.1` 
        alpine:
          - '3.12'
    steps:
      - name: "Checkout source code at current commit"
        uses: actions/checkout@v2
      - name: "Build and push docker image to DockerHub"
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ github.repository }}-apkbuild
          dockerfile: apk/Dockerfile-${{matrix.alpine}}
          tags: ${{matrix.alpine}}
          registry: registry-1.docker.io
          tag_with_ref: true
          tag_with_sha: true
